[build]
  base = "web"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--loglevel=error"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_CONFIG_IGNORE_OPTIONAL = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
